version: '3'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/node_modules
    command: sleep infinity
    ports:
      - 3000:3000
      - 24678:24678

volumes:
  node_modules:
